#!/usr/bin/env python

# run.sh: runs the actual submission

#python3 remote_player.py & python3 test_driver.py
#cat - | ./remote_player.py & sleep 1 && ./test_driver.py
python3 test_driver.py & sleep 1 & python3 remote_player.py
